name: g4
services:
  postgres:
    image: postgres:16-alpine
    container_name: g4-db
    ports:
      - ${POSTGRES_PORT}:5432
    volumes:
      - g4-data:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_DB=${POSTGRES_DB}
    networks:
      - g4-net
  backend:
    depends_on:
      - postgres
    image: putterbs/preflight-backend:latest
    container_name: g4-backend
    ports:
      - ${PORT}:3000
    networks:
      - g4-net
    environment:
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_PORT=${POSTGRES_PORT}
      - POSTGRES_HOST=${POSTGRES_HOST}
      - POSTGRES_APP_USER=${POSTGRES_APP_USER}
      - POSTGRES_APP_PASSWORD=${POSTGRES_APP_PASSWORD}
  frontend:
    depends_on:
      - backend
    image: putterbs/preflight-frontend:latest
    container_name: g4-frontend
    ports:
      - ${NGINX_PORT}:5173
    networks:
      - g4-net
    environment:
      - NGINX_PROXY=${NGINX_PROXY}
      - NGINX_PORT=5173
volumes:
  g4-data:
networks:
  g4-net:
